---
title: "NCAA and NBA Assignment"
output: html_document
date: "2025-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(car)
library(class)
library(caret)
```

```{r}
NCAA <- read.csv("per_caps_NCAAF.csv")
NCAA
```

```{r}
# 1 Concessions
model1 <- lm(pccon ~ wp + owp + confgame + Thurs + Friday + smallconf + bigconf + hf + absline + total, data = NCAA)
summary(model1)

# Overall, this model is statistically significant at the 1% level. The most significant variables in this model are Friday games, the abs line, and home favorite dummy variable. Friday games are significant at the 5% level, wit ha coefficient of 1.24, suggesting that concession spending increases during Friday games compared to other days.

# The absolute value of point spread (abs line) is significant at the 5% level, with a coefficient of -0.05910, indicating that as per capita concession expenditure increases, the abs line will decrease by 0.05910.

# The home favorite dummy is significant at the 10% level, indicating fans spend more on concessions if the home team is likely to win.
```

```{r}
#1.2 Novelties
model2 <- lm(pcnov ~ wp + owp + confgame + Thurs + Friday + smallconf + bigconf + hf + absline + total, data = NCAA)
summary(model2)

# The model as a whole is not statistically significant, as it surpasses the 1%, 5%, and 10% significance levels (18%). According to this model, significant predictors would be Thursday games (5% level), and Friday games (10% level). However, since this model is not statistically significant, it wouldn't be ideal to highlight coefficients for any of these variables.
```

```{r}
# 1.3 VIF
car::vif(model1)

# For pccon (per capita expenditure on concessions), the only issue of multicollinearity appears to be in the smallconf games, to which teh value exceeds the 5 threshold. While it is slightly above 5, there is a chance that there is multicollinearity in this model. Therefore, if we adjust the model, smallconf will be removed to account for this.

car::vif(model2)

# For pcnov (per capita expenditure on novelties), the only issue of multicollinearity appears to be in the smallconf games as well. The value exceeds 5, indicating there is slight multicollinearity in this model. Therefore, we must remove smallconf from the model to account for this.
```

```{r}
# Concessions Adjusted
model3 <- lm(pccon ~ wp + owp + confgame + Thurs + Friday + bigconf + hf + absline + total, data = NCAA)
summary(model3)
car::vif(model3)

# The model remains significant at the 1% level, this time significant variables are win percentage, Friday games, home favorite dummy, and absline. Home win percentage, Friday games, and absline are significant at the 5% level, home favorite dummy variable is significant at the 10% level. All in all, the model has been altered to accurately reduce multicollinearity, as none of the VIF totals exceed 5.

# The coefficient for winning percentage suggests that as home winning percentage increases, so will per capita expenditure.
# The coefficient for Friday games suggests that per capita expenditure on concessions will increase.
# The coefficient for absline suggests that per capita expenditure on concessions will increase as absline decreases.
# The coefficient for home favorite suggests that per capita expenditure on concessions will increase, if the home team is the favorite.
```

```{r}
# Novelties Adjusted
model4 <- lm(pcnov ~ wp + owp + confgame + Thurs + Friday + bigconf + hf + absline + total, data = NCAA)
summary(model4)
car::vif(model4)

# The model remains statistically insignificant, a p-value of 12%. This is far less than the previous model, therefore this indicates that smallconf games had an impact on the initial model. The accurate predictors, despite the insignificance of the model, are Thursday games (1%), Friday games (10%). Thursday games became more significant, jumping from 5% to 1%. In addition, multicollinearity has been accounted for, as all VIF values are less than 5.

# All in all, these variables are not the greatest predictors of per capita expenditure on novelties compared to the per capita expenditure on concessions model.
```

```{r}
# NBA KNN
NBA <- read.csv("NBA_Stats_Salary_4_2_23.csv")
NBA
```

```{r}
# Function
normalize <- function(x) {
  return((x-min(x)) / (max(x) - min(x)))
}


# Mutations
NBA <- NBA %>%
  mutate(
    Cap.Hit = normalize(Cap.Hit),
    Age = normalize(Age),
    G = normalize(G),
    MP = normalize(MP),
    PER = normalize(PER),
    TS = normalize(TS),
    X3PAr = normalize(X3PAr),
    FTr = normalize(FTr),
    ORB = normalize(ORB),
    DRB = normalize(DRB),
    TRB = normalize(TRB),
    AST = normalize(AST),
    STL = normalize(STL),
    BLK = normalize(BLK),
    TOV = normalize(TOV),
    USG = normalize(USG),
    OWS = normalize(OWS),
    DWS = normalize(DWS),
    WS = normalize(WS),
    WS.48 = normalize(WS.48),
    OBPM = normalize(OBPM),
    DBPM = normalize(DBPM),
    BPM = normalize(BPM),
    VORP = normalize(VORP)
  )

summary(NBA)

# Labels

Position <- NBA$Pos
x_vars <- NBA %>% select(-Pos)

set.seed(1234)
sample_index <- sample(nrow(NBA), round(nrow(NBA)*.75), replace = FALSE)
NBA_train <- x_vars[sample_index, ]
NBA_test <- x_vars[-sample_index, ]
train_labels <- Position[sample_index]
test_labels <- Position[-sample_index]

Pos_pred <-
  knn(
    train = NBA_train,
    test = NBA_test,
    cl = train_labels,
    k = 3
  )

# Table
Pos_pred_table <- table(test_labels, Pos_pred)
sum(diag(Pos_pred_table)/ nrow(NBA_test))

confusionMatrix(Pos_pred, as.factor(test_labels))

# When you change k=3 to k=4 or k=5, the accuracy increases only as you change from k=4 to k=5, while k=3 to k=4 actually decreased. In addition, the table predictions change based on position. Some positions see increases or decreases as k increases, for example Center was at 112 at k=3, but decreases to 108 at k=4. Then at k=5, Center increased to 115. Some fluctuations in the data, but accuracy is important, and that decreased from k=3 to k=4, but increased from k=4 to k=5.

#Accuracy Statistics
# k=3: 60.92%
# K=4: 58.61%
# k=5: 60.10%
```

