---
title: "Week 2 Assignment 1968 Half Season Simulation"
output: html_document
date: "2025-09-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(Lahman)
```

```{r}
# Reading Data
fields <- read.csv("fields.csv")
data1968 <- read.csv("all1968.csv",
                     col.names = pull(fields,Header),
                     na = character())

data1968
```

```{r}
# Preparing Data
data1968 %>%
  mutate(RUNS = AWAY_SCORE_CT + HOME_SCORE_CT,
         HALF.INNING = paste(GAME_ID, INN_CT, BAT_HOME_ID),
         RUNS.SCORED =
           (BAT_DEST_ID > 3) + (RUN1_DEST_ID > 3) +
           (RUN2_DEST_ID > 3) + (RUN2_DEST_ID > 3)) ->
           data1968
```


```{r}
# Preparing Data
data1968 %>%
  group_by(HALF.INNING) %>%
  summarize(Outs.Inning = sum(EVENT_OUTS_CT),
            Runs.Inning = sum(RUNS.SCORED),
            Runs.Start = first(RUNS),
            MAX.RUNS = Runs.Inning + Runs.Start) ->
  half_innings
```

```{r}
# Preparing Data
data1968 %>%
  inner_join(half_innings, by = "HALF.INNING") %>%
  mutate(RUNS.ROI = MAX.RUNS - RUNS) ->
  data1968
```

```{r}
# Preparing Data
data1968 %>%
  mutate(BASES =
         paste(ifelse(BASE1_RUN_ID > "",1,0),
               if_else(BASE2_RUN_ID > "",1,0),
               if_else(BASE3_RUN_ID > "",1,0), sep = ""),
         STATE = paste(BASES, OUTS_CT)) ->
  data1968
```

```{r}
# Preparing Data
data1968 %>%
  mutate(NRUNNER1 =
           as.numeric(RUN1_DEST_ID == 1 | BAT_DEST_ID == 1),
         NRUNNER2 =
           as.numeric(RUN1_DEST_ID == 2 | RUN2_DEST_ID == 2 |
                        BAT_DEST_ID == 2),
         NRUNNER3 =
           as.numeric(RUN1_DEST_ID == 3 | RUN2_DEST_ID == 3 | RUN3_DEST_ID == 3 | BAT_DEST_ID == 3),
         NOUTS = OUTS_CT + EVENT_OUTS_CT,
         NEW.BASES = paste(NRUNNER1, NRUNNER2,
                           NRUNNER3, sep = ""),
         NEW.STATE = paste(NEW.BASES, NOUTS)) -> data1968


# Restrict attention to plays where there is a change between STATE AND NEW STATE or If runs are scored on play
data1968 %>%
  filter((STATE != NEW.STATE) | (RUNS.SCORED > 0)) -> data1968

#Remove extra inning dues to the automatic runner (ghost on second). This is because retrosheet does not encode these runners as BASE2_RUN_ID.
data1968 %>%
  filter(INN_CT <= 7) -> data1968

# Finally, we will restrict half innings to only those that are complete and events that are batter events (no stolen bases, balks, wild pitches, etc).
data1968 %>%
  filter(Outs.Inning ==3, BAT_EVENT_FL == TRUE) -> data1968c
```

```{r}
# Preparing Data
data1968c %>%
  group_by(STATE) %>%
  summarise(Mean = mean(RUNS.ROI)) %>%
  mutate(Outs = substr(STATE, 5,5)) %>%
  arrange(Outs) -> RUNS

RUNS_out <- matrix(round(RUNS$Mean,2),8,3)
dimnames(RUNS_out)[[2]] <- c("0 outs", "1 outs", "2 outs")
dimnames(RUNS_out)[[1]] <- c("000", "001", "010", "011", "100", "101", "110", "111")

RUNS_out
```

```{r}
# Question 2: Creating the Transition T and Probability Matrix
data1968c <- data1968c %>%
  mutate(NEW.STATE = gsub("[0-1]{3} 3", "3", NEW.STATE))

# Transition T Matrix
T_matrix <- data1968c %>%
  select(STATE, NEW.STATE) %>%
  table()

view(T_matrix)

# Probability Matrix
P_matrix <- prop.table(T_matrix, 1)
P_matrix <- rbind(P_matrix, c(rep(0,24),1))

view(P_matrix)

# Probability Matrix (Transition Probabilities at the "000" states, no runners and no outs).
P_matrix %>%
  as_tibble(rownames = "STATE") %>%
  filter(STATE == "000 0") %>%
  gather(key = "NEW.STATE", value = "Prob", -STATE) %>%
  filter(Prob > 0) %>%
  arrange(desc(Prob))
```



```{r}
# Question 3: Creating Run Matrix utilziing Markov Chain
count_runners_out <- function(s) {
  s %>%
    str_split("") %>% #split each character separtely
    pluck(1) %>% #pluck the first and only item (vector) from list
    as.numeric() %>% #convert to numeric
    sum(na.rm = TRUE) #sum
}

runners_out <- sapply(row.names(T_matrix),
                      count_runners_out)[-25]

R <- outer(runners_out +1, runners_out, FUN = "-")
R <- cbind(R, rep(0,24))

R

# Simulating Markov Chain
# Question 4: Simulate Half Inning Function
simulate_half_inning <- function(P, R, start = 1) {
  s <- start
  path <- NULL
  runs <- 0
  while (s < 25) {
    s.new <- sample(1:25, size = 1, prob = P[s, ])
    path <- c(path, s.new)
    runs <- runs + R[s, s.new]
    s <- s.new
  }
  return(runs)
}

simulate_half_inning(P_matrix, R, 1) # test
```
```{r}
# Question 5 Simulating 10,000 Half Innings
set.seed(123)
RUNS <- replicate(10000, simulate_half_inning(T_matrix,R))
table(RUNS)

# 5 or more runs scored in 24 + 15 + 2 + 2, this equals 43 half innings. Therefore, the chance of scoring five or more runs would be 0.0043.

sum(RUNS >=5) / 10000

mean(RUNS)

# Over 10,000 half innings, the average amount of runs scored was 0.3453.
```

```{r}
# Question 5 Continued: Viewing Run Expectancy Matrix
set.seed(123)
RUNS.j <- function(j) {
  mean(replicate(10000, simulate_half_inning(T_matrix, R, j)))
}

RE_bat <- sapply(1:24, RUNS.j) %>%
  matrix(nrow = 8, ncol = 3, byrow = TRUE,
         dimnames = list(c("000", "001", "010", "011",
                           "100", "101", "110", "111"),
                         c("0 outs", "1 out", "2 outs")))
round(RE_bat, 2)
```

```{r}
# Question 6 - Comparing 1968 Run Expectancy Matrix to the 2021 Run Expectancy Matrix
RE_bat_2021 <- t(matrix(c(0.49,0.26,0.10,
                          1.38, 0.94, 0.37,
                          1.12, 0.68, 0.32,
                          1.99, 1.37, 0.58,
                          0.88, 0.52, 0.23,
                          1.75, 1.10, 0.46,
                          1.54, 0.90, 0.43,
                          2.37, 1.64, 0.81), 3, 8))

RE_bat - RE_bat_2021
sqrt(mean(RE_bat - RE_bat_2021)^2)



# In 1968, the chances of scoring runs with the bases loaded with any outs (0, 1, and 2) were far lower than the 2021 data that is shown. In the 1968 simulation, it is interesting to note that the expected run value of that half inning from the initial condition is roughly highest when there are 0 outs, and the bases are loaded. The same goes for the 2021 data. However there is a notable gap when you subtract the 2021 data from the 1968 table, with a difference of -0.6596. This illustrates that in 2021, run expectancy for that half inning (based on simulation) is far greater than 1968. This is a glaring example of how the game has changed since then.

# However, they also share the same similarity that when there are men on first and second base, there is a high expected run value for that half inning with 0 outs as well. (1968: 1.53) (2021: 1.99). 

# RMSE: The difference is 0.221075 runs, which is notable considering the gap between 1968 and 2021 (baseball adaptations). All in all, they share some similarities in the same situations, but there is clear disparity between the two seasons.
```


