---
title: 'Assignment 6: Swing per Pitch Heatmap'
output: html_document
date: "2024-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(baseballr)
library(ggplot2)
```
```{r}
Statcast <- read_csv("statcastAugust2019.csv")
```
```{r}
# Question A
APStatcast1 <- scrape_statcast_savant_batter("2019-07-01", "2019-07-08",batter = "405395")
APStatcast2 <- scrape_statcast_savant_batter("2019-07-09", "2019-07-16",batter = "405395")
APStatcast3 <- scrape_statcast_savant_batter("2019-07-17","2019-07-23", batter = "405395")
APStatcast4 <- scrape_statcast_savant_batter("2019-07-24","2019-07-29", batter = "405395")
APStatcast5 <- scrape_statcast_savant_batter("2019-07-30", "2019-07-31", batter = "405395")

Statcast <- rbind(APStatcast1, APStatcast2, APStatcast3, APStatcast4, APStatcast5)
```

```{r}
# Question B
Statcast %>% filter(description != "blocked_ball") -> AlbertPujolsStatcast
```

```{r}
#Question C
AlbertPujolsStatcast %>%
  mutate(swing = case_when(
    type == "S" & description == "called_strike" ~ FALSE,
    type == "B" ~ FALSE,
    type == "X" ~ TRUE,
    type == "S" ~ TRUE)) -> AlbertPujolsStatcast
```

```{r}
zones <- AlbertPujolsStatcast %>%
  group_by(zone) %>%
  summarize(
    N = n(),
    right_edge = min(1.5, max(plate_x)),
    left_edge = max(-1.5, min(plate_x)),
    top_edge = min(4, quantile(plate_z, 0.95, na.rm = TRUE)),
    bottom_edge = max(1, quantile(plate_z, 0.05, na.rm = TRUE)),
    swing_rate = sum(swing == TRUE) / n(),
    plate_x = mean(plate_x),
    plate_z = mean(plate_z))
```


```{r}
plate_width <- 17 + (9/pi)
k_zone_plot <- ggplot(NULL, aes(x = plate_x, y = plate_z)) +
  geom_rect(xmin = -(plate_width/2)/12,
  xmax = (plate_width/2)/12,
  ymin = 1.5,
  ymax = 3.6, color = "red", alpha = 0) +
  coord_equal() +
  scale_x_continuous("Horizontal location (ft.)",
                     limits = c(-2, 2)) +
  scale_y_continuous("Vertical location (ft.)",
                     limits = c(0,5))
```


```{r}
library(ggrepel)
k_zone_plot %+% zones +
  geom_rect(aes(xmax = right_edge, xmin = left_edge,
                ymax = top_edge, ymin = bottom_edge,
                fill = swing_rate, alpha = swing_rate),
            color = "maroon") +
  geom_text_repel(size = 3, aes(label = round(swing_rate, 2),
                                color = swing_rate < 0.5)) +
  scale_fill_gradient(low = "blue", high = "red") +
  scale_color_manual(values = c("white", "black")) +
  guides(color = FALSE, alpha = FALSE) +
  ggtitle("Albert Pujols Swing Per Pitch during July 2019")
  ggsave("Albert Pujols Swing Per Pitch during July 2019.pdf")
```