---
title: "SAL 602 Project"
author: "Andrew Fish"
date: "2024-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(tidyverse)
library(Lahman)
library(baseballr)
library(readr)
library(ggrepel)
```

The following sections of code is the data scraping and data manipulation of the statcast data used in this project.

```{r}
masterID <- read_csv("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 7/masterid.csv")
```

```{r}
##scrapes a month with defined start date so only getting regular season data
scrapeStatcastFirstmonth <- function(year, month, start_date, playerID) {
  if (month == 4) {
    scrape1 <- scrape_statcast_savant_batter(start_date,
                                             paste(as.character(year), "-0", as.character(month), "-07", sep = ""),
                                             batterid = playerID)
    
    scrape2 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-08", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-14", sep = ""),
                                             batterid = playerID)
    
    scrape3 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-15", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-21", sep = ""),
                                             batterid = playerID)
    
    scrape4 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-22", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-28", sep = ""),
                                             batterid = playerID)
    
    scrape5 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-29", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-30", sep = ""),
                                             batterid = playerID)
    
    statcastScrape <- rbind(scrape1, scrape2, scrape3, scrape4, scrape5)
  }
  if (month == 3) {
    start_date %>% strsplit("-") -> split_date
    day <- as.numeric(split_date[[1]][3])
    if (30 - day < 7) {
      statcastScrape <- scrape_statcast_savant_batter(start_date,
                                                      paste(as.character(year), "-0", as.character(month), "-30", sep = ""),
                                                      batterid = playerID)
    }
    else if ((30 - day <14) & (30 - day >= 7)) {
      scrape1 <- scrape_statcast_savant_batter(start_date,
                                               paste(as.character(year), "-0", as.character(month), "-23", sep = ""),
                                               batterid = playerID)
      
      scrape2 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-24", sep = ""),
                                               paste(as.character(year), "-0", as.character(month), "-30", sep = ""),
                                               batterid = playerID)
      statcastScrape <- rbind(scrape1, scrape2)
    }
  }
  return(statcastScrape)
}
```

```{r}
##scrapes month with end date so only getting regular season data
scrapeStatcastLastmonth <- function(year, month, end_date, playerID) {
  if (month == 9) {
    scrape1 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-01", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-07", sep = ""),
                                             batterid = playerID)
    scrape2 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-08", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-14", sep = ""),
                                             batterid = playerID)
    scrape3 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-15", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-21", sep = ""),
                                             batterid = playerID)
    scrape4 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-22", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-28", sep = ""),
                                             batterid = playerID)
    scrape5 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-29", sep = ""),
                                             end_date)
    statcastScrape <- rbind(scrape1, scrape2, scrape3, scrape4, scrape5)
  }
  if (month == 10) {
    statcastScrape <- scrape_statcast_savant_batter(paste(as.character(year), "-", as.character(month), "-01", sep = ""),
                                             end_date)
    
  }
  return(statcastScrape)
}
```

```{r}
##scrapes 1 month worth of statcast data use if statements to help generalize format since assuming not inputting correct format
scrapeStatcastmonth <- function(year, month, playerID){
  if (month < 10) {
    scrape1 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-01", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-07", sep = ""),
                                             batterid = playerID)
    scrape2 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-08", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-14", sep = ""),
                                             batterid = playerID)
    scrape3 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-15", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-21", sep = ""),
                                             batterid = playerID)
    scrape4 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-22", sep = ""),
                                             paste(as.character(year), "-0", as.character(month), "-28", sep = ""),
                                             batterid = playerID)
    if (month %in% c(3, 5, 7, 8)) {
      scrape5 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-29", sep = ""),
                                               paste(as.character(year), "-0", as.character(month), "-31", sep = ""),
                                               batterid = playerID)
    }
    else if (month %in% c(4, 6, 9)) {
      scrape5 <- scrape_statcast_savant_batter(paste(as.character(year), "-0", as.character(month), "-29", sep = ""),
                                               paste(as.character(year), "-0", as.character(month), "-30", sep = ""),
                                               batterid = playerID)
    }
  }
  else if (month == 10) {
    scrape1 <- scrape_statcast_savant_batter(paste(as.character(year), "-", as.character(month), "-01", sep = ""),
                                             paste(as.character(year), "-", as.character(month), "-07", sep = ""),
                                             batterid = playerID)
    scrape2 <- scrape_statcast_savant_batter(paste(as.character(year), "-", as.character(month), "-08", sep = ""),
                                             paste(as.character(year), "-", as.character(month), "-14", sep = ""),
                                             batterid = playerID)
    scrape3 <- scrape_statcast_savant_batter(paste(as.character(year), "-", as.character(month), "-15", sep = ""),
                                             paste(as.character(year), "-", as.character(month), "-21", sep = ""),
                                             batterid = playerID)
    scrape4 <- scrape_statcast_savant_batter(paste(as.character(year), "-", as.character(month), "-22", sep = ""),
                                             paste(as.character(year), "-", as.character(month), "-28", sep = ""),
                                             batterid = playerID)
    scrape5 <- scrape_statcast_savant_batter(paste(as.character(year), "-", as.character(month), "-29", sep = ""),
                                             paste(as.character(year), "-", as.character(month), "-30", sep = ""),
                                             batterid = playerID)
  }
  statcastScrape <- rbind(scrape1, scrape2, scrape3, scrape4, scrape5)
  return(statcastScrape)
}
```

```{r}
#scrapes full year by calling month function in loop
scrapeStatcastyear <- function(year, month, year_start, year_end, playerID){
  for (i in 1:length(month)) {
    Sys.sleep(5)
    if (i == 1) {
      yearScrape <- scrapeStatcastFirstmonth(year, month[i], year_start, playerID)
    }
    else if (i == length(month)) {
      holderScrape <- scrapeStatcastLastmonth(year, month[i], year_end, playerID)
      yearScrape %>% bind_rows(holderScrape) -> yearScrape
    }
    else {
      holderScrape <- scrapeStatcastmonth(year, month[i], playerID)
      yearScrape %>% bind_rows(holderScrape) -> yearScrape
    }
  }
  return(yearScrape)
}
```

```{r}
##months of each mlb season
months2015 <- c(4:10)
months2016 <- c(4:10)
months2017 <- c(4:10)
months2018 <- c(3:10)
months2019 <- c(3:9)
months2021 <- c(4:10)
months2022 <- c(4:10)
months2023 <- c(3:10)
months2024 <- c(3:9)
```

```{r}
judge <- 592450
ohtani <- 660271
acuna <- 660670
goldy <- 502671
harper <- 547180
trout <- 545361
belly <- 641355
betts <- 605141
yelich <- 592885
altuve <- 514888
stanton <- 519317
bryant <- 592178
dondalson <- 518626
```

```{r}
##scrapes each individual year with MVP winner as player
donaldson2015 <- scrapeStatcastyear(2015, months2015, "2015-04-05", "2015-10-04", dondalson)
harper2015 <- scrapeStatcastyear(2015, months2015, "2015-04-05", "2015-10-04", harper)

trout2016 <- scrapeStatcastyear(2016, months2016, "2016-04-03", "2016-10-01", trout)
bryant2016 <- scrapeStatcastyear(2016, months2016, "2016-04-03", "2016-10-01", bryant)

altuve2017 <- scrapeStatcastyear(2017, months2017, "2017-04-02", "2017-10-01", altuve)
stanton2017 <- scrapeStatcastyear(2017, months2017, "2017-04-02", "2017-10-01", stanton)

betts2018 <- scrapeStatcastyear(2018, months2018, "2018-03-29", "2018-10-01", betts)
yelich2018 <- scrapeStatcastyear(2018, months2018, "2018-03-29", "2018-10-01", yelich)

trout2019 <- scrapeStatcastyear(2019, months2019, "2019-03-20", "2019-09-29", trout)
belly2019 <- scrapeStatcastyear(2019, months2019, "2019-03-20", "2019-09-29", belly)

ohtani2021 <- scrapeStatcastyear(2021, months2021, "2021-04-01", "2021-10-03", ohtani)
harper2021 <- scrapeStatcastyear(2021, months2021, "2021-04-01", "2021-10-03", harper)

judge2022 <- scrapeStatcastyear(2022, months2022, "2022-04-07", "2022-10-05", judge)
goldy2022 <- scrapeStatcastyear(2022, months2022, "2022-04-07", "2022-10-05", goldy)

ohtani2023 <- scrapeStatcastyear(2023, months2023, "2023-03-30", "2023-10-01", ohtani)
acuna2023 <- scrapeStatcastyear(2023, months2023, "2023-03-30", "2023-10-01", acuna)

judge2024 <- scrapeStatcastyear(2024, months2024, "2024-03-28", "2024-09-30", judge)
ohtani2024 <- scrapeStatcastyear(2024, months2024, "2024-03-28", "2024-09-30", ohtani)
```

```{r}
##re filter by batter
donaldson2015 %>%
  filter(batter == 518626) -> donaldson2015
harper2015 %>%
  filter(batter == 547180) -> harper2015
season2015 <- rbind(donaldson2015, harper2015)

trout2016 %>%
  filter(batter == 545361) -> trout2016
bryant2016 %>%
  filter(batter == 592178) -> bryant2016
season2016 <- rbind(trout2016, bryant2016)

altuve2017 %>%
  filter(batter == 514888) -> altuve2017
stanton2017 %>%
  filter(batter == 519317) -> stanton2017
season2017 <- rbind(altuve2017, stanton2017)

betts2018 %>%
  filter(batter == 605141) -> betts2018
yelich2018 %>%
  filter(batter == 592885) -> yelich2018
season2018 <- rbind(betts2018, yelich2018)

trout2019 %>%
  filter(batter == 545361) -> trout2019
belly2019 %>%
  filter(batter == 641355) -> belly2019
season2019 <- rbind(trout2019, belly2019)

ohtani2021 %>%
  filter(batter == 660271) -> ohtani2021
harper2021 %>%
  filter(batter == 547180) -> harper2021
season2021 <- rbind(ohtani2021, harper2021)

judge2022 %>%
  filter(batter == 592450) -> judge2022
goldy2022 %>%
  filter(batter == 502671) -> goldy2022
season2022 <- rbind(judge2022, goldy2022)

ohtani2023 %>%
  filter(batter == 660271) -> ohtani2023
acuna2023 %>%
  filter(batter == 660670) -> acuna2023
season2023 <- rbind(ohtani2023, acuna2023)

judge2024 %>%
  filter(batter == 592450) -> judge2024
ohtani2024 %>%
  filter(batter == 660271) -> ohtani2024
season2024 <- rbind(judge2024, ohtani2024)
```

```{r}
mvpWinners <- rbind(season2015, season2016, season2017, season2018, season2019,
                    season2021, season2022, season2023, season2024)
```

```{r}
write_csv(mvpWinners, "C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 8/mvpWinners.csv")
```

The next section of the code will be data manipulation and ShinyApp
```{r}
mvpWinners <- read_csv("mvpWinners.csv")
masterID <- read_csv("masterid.csv")

##want to have a column for exit velo now only have x,y,z components
##formula taken from fangraphs to find exit velo from components
mvpWinners %>%
  mutate(x2 = vx0 ^ 2,
         y2 = vy0 ^ 2,
         z2 = vz0 ^ 2,
         exit_velo = sqrt(x2 + y2 + z2) * 0.6818) -> mvpWinners

##possible batters for drop down menu
mvpWinners %>%
  group_by(batter) %>%
  summarise() %>%
  inner_join(masterID, by = c("batter" = "mlb_id")) %>%
  select(batter, mlb_name) %>%
  arrange(mlb_name) -> possibleBatters

possibleBattersList <- possibleBatters$batter
names(possibleBattersList) <- possibleBatters$mlb_name

##creating strike zone
plate_width <- 17 + (9 / pi)
k_zone_plot <- ggplot(NULL, aes(x = plate_x, plate_z)) +
  geom_rect(xmin = -(plate_width / 2) / 12,
            xmax = (plate_width / 2) / 12,
            ymin = 1.5,
            ymax = 3.6, color = "black", alpha = 0) +
  coord_equal() +
  scale_x_continuous("Horizontal Location (ft.)",
                     limits = c(-2, 2)) +
  scale_y_continuous("Vertical Location (ft.)",
                     limits = c(0, 5))


ui <- fluidPage(
  titlePanel("Exit Velocity of MVP Winners - 2015-2024 (Excluding 2020)"),
  sidebarLayout(
    sidebarPanel(position = "left",
                  selectInput(inputId = "selectBatter",
                              label = h3("Batter"),
                              choices = possibleBattersList,
                              selected = 660271)
    ),
    sidebarPanel(position = "left",
      checkboxGroupInput(inputId = "years",
                         label = "Year",
                         choices = list("2015: Donaldson, Harper" = 2015,
                                        "2016: Trout, Bryant" = 2016,
                                        "2017: Altuve, Stanton" = 2017,
                                        "2018: Betts, Yelich" = 2018,
                                        "2019: Trout, Bellinger" = 2019,
                                        "2021: Ohtani, Harper" = 2021,
                                        "2022: Judge, Goldschmidt" = 2022,
                                        "2023: Ohtani, Acuña" = 2023,
                                        "2024: Judge, Ohtani" = 2024),
                         selected = 2024),
      helpText("To get image to show must have year selected to the year the player won MVP.
               You can have multiple years selected if player won multiple MVPs during timeframe.
               To help MVP Winners are labeled with each year.")
    )
  ),
  mainPanel(position = "right",
    plotOutput(outputId = "batterEV"),
    plotOutput(outputId = "exitveloHist")
  )
)


server <- function(input, output) {
  SelectedBatterReactive <- reactive({
    mvpWinners %>% filter(batter == input$selectBatter)
  })
  
  output$batterEV <- renderPlot({
    SelectedBatterReactive() %>%
      filter(game_year %in% input$years) -> selectedYears
    
    zones <- selectedYears %>%
      group_by(zone) %>%
      summarize(
        N = n(),
        right_edge = min(1.5, max(plate_x)),
        left_edge = max(-1.5, min(plate_x)),
        top_edge = min(5, quantile(plate_z, 0.95, na.rm = TRUE)),
        bottom_edge = max(0, quantile(plate_z, 0.05, na.rm = TRUE)),
        avg_ev = sum(exit_velo) / n(),
        plate_x = mean(plate_x),
        plate_z = mean(plate_z))
    
    k_zone_plot %+% zones +
      geom_rect(aes(xmax = right_edge, xmin = left_edge,
                    ymax = top_edge, ymin = bottom_edge,
                    fill = avg_ev, alpha = avg_ev),
                color = "darkgreen") +
      geom_text_repel(size = 4, aes(label = round(avg_ev, 2),
                                    color = avg_ev < 0.5)) +
      scale_fill_gradient(low = "blue", high = "red") +
      scale_color_manual(values = c("white", "black")) +
      guides(color = FALSE, alpha = FALSE) +
      ggtitle("Exit Velocity by Zone")
  })
  
  output$exitveloHist <- renderPlot({
    SelectedBatterReactive() %>%
      filter(game_year %in% input$years) -> selectedYears

    ggplot(selectedYears, aes(x = exit_velo, color = pitch_type)) +
      geom_histogram() + ggtitle("Exit Velocity Distribution") +
      xlab("Exit Velocity (MPH)") + ylab("n")
  })
}

shinyApp(ui = ui, server = server)
```

