---
title: "Swing"
output: html_document
date: "2024-12-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(tidyverse)
library(baseballr)
library(ggrepel)
library(readr)
library(plotly)
install.packages("plotly")
```

```{r}
mvpWinners %>%
  filter(description != "blocked_ball") %>%
  mutate(swing = case_when(
    type == "S" & description == "called_strike" ~ FALSE,
    type == "X" | type == "S" ~ TRUE,
    type == "B" ~ FALSE))-> mvpWinners
```

```{r}
plate_width <- 17 + (9 / pi)
k_zone_plot <- ggplot(NULL, aes(x = plate_x, plate_z)) +
  geom_rect(xmin = -(plate_width / 2) / 12,
            xmax = (plate_width / 2) / 12,
            ymin = 1.5,
            ymax = 3.6, color = "black", alpha = 0) +
  coord_equal() +
  scale_x_continuous("Horizontal Location (ft.)",
                     limits = c(-2, 2)) +
  scale_y_continuous("Vertical Location (ft.)",
                     limits = c(0, 5))
```



```{r}
ui <- fluidPage(
  titlePanel("MVP Swing Rates"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "selectPlayer",
                  label = h3("Select Player"),
                  choices = unique(mvpWinners$player_name),
                  selected = NULL),
      
      checkboxGroupInput(inputId = "types",
                         label = h3("Types of Outcomes"),
                         choices = list("S" = "S",
                                        "B" = "B",
                                        "X" = "X"),
                         selected = c("S", "B", "X"))
    ),
    mainPanel(
      plotOutput(outputId = "swingRateChart"),
      plotOutput(outputId = "launchSpeedAnglePlot")
    )
  )
)

server <- function(input, output) {
  
  output$swingRateChart <- renderPlot({
    req(input$selectPlayer)
    
    mvpWinners %>%
      filter(player_name == input$selectPlayer) %>%
      filter(type %in% input$types) -> SelectedPitchResults
    
    zones <- SelectedPitchResults %>%
      group_by(zone) %>%
      summarize(
        N = n(),
        right_edge = min(1.5, max(plate_x)),
        left_edge = max(-1.5, min(plate_x)),
        top_edge = min(5, quantile(plate_z, 0.95, na.rm = TRUE)),
        bottom_edge = max(0, quantile(plate_z, 0.05, na.rm = TRUE)),
        swing_pct = sum(swing == TRUE) / n(),
        plate_x = mean(plate_x),
        plate_z = mean(plate_z))
    
    k_zone_plot %+% zones +
      geom_rect(aes(xmax = right_edge, xmin = left_edge,
                    ymax = top_edge, ymin = bottom_edge,
                    fill = swing_pct, alpha = swing_pct),
                color = "darkgreen") +
      geom_text_repel(size = 3, aes(label = round(swing_pct, 2),
                                    color = swing_pct < 0.5)) +
      scale_fill_gradient(low = "blue", high = "red") +
      scale_color_manual(values = c("white", "black")) +
      guides(color = FALSE, alpha = FALSE) +
      ggtitle(paste("Swing Rates for", input$selectPlayer))
  })
  
  output$launchSpeedAnglePlot <- renderPlot({
    req(input$selectPlayer)
    
    player_data <- mvpWinners %>%
      filter(player_name == input$selectPlayer)
    
    ggplot(player_data, aes(x = launch_speed, y = launch_angle, color = cut(launch_speed, breaks = c(-Inf, 90, 100, Inf), labels = c("Blue", "Gray", "Red")))) +
      geom_point(alpha = 0.5) +
      scale_color_manual(values = c("Blue" = "blue", "Gray" = "gray", "Red" = "red")) +
      labs(title = paste("Launch Speed vs. Launch Angle for", input$selectPlayer),
           color = "Launch Speed") +
      xlab("Launch Speed") +
      ylab("Launch Angle")
  })
  
}

shinyApp(ui = ui, server = server)


```

