---
title: "Week 7"
output: html_document
date: "2024-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(baseballr)
library(readr)
library(ggrepel)
library(shiny)
library(rsconnect)
masterid <- read_csv("masterid.csv")
```

```{r}
## Write CSV after scraping reminder
StatcastJuly1 <- scrape_statcast_savant_batter_all("2019-07-01", "2019-07-08")
StatcastJuly2 <- scrape_statcast_savant_batter_all("2019-07-09", "2019-07-16")
StatcastJuly3 <- scrape_statcast_savant_batter_all("2019-07-17", "2019-07-23")
StatcastJuly4 <- scrape_statcast_savant_batter_all("2019-07-24", "2019-07-29")
StatcastJuly5 <- scrape_statcast_savant_batter_all("2019-07-30", "2019-07-31")

Statcast <- rbind(StatcastJuly1, StatcastJUly2, StatcastJuly3, StatcastJuly4, StatcastJUly5)
```

```{r}
Statcast %>%
  filter(description != "blocked_ball") -> Statcast
```

```{r}
Statcast %>%
mutate(swing = case_when(
    type == "S" & description == "called_strike" ~ FALSE,
    type == "B" ~ FALSE,
    type == "X" ~ TRUE,
    type == "S" ~ TRUE)) -> SwingStatcast
View(SwingStatcast)
```

```{r}
## Strike Zone Creation
  plate_width <- 17 + (9/pi)
  k_zone_plot <- ggplot(NULL, aes(x = plate_x, y = plate_z)) +
  geom_rect(xmin = -(plate_width/2)/12,
  xmax = (plate_width/2)/12,
  ymin = 1.5,
  ymax = 3.6, color = "red", alpha = 0) +
  coord_equal() +
  scale_x_continuous("Horizontal location (ft.)",
                     limits = c(-2, 2)) +
  scale_y_continuous("Vertical location (ft.)",
                     limits = c(0,5))
```

```{r}
## Batter List
SwingStatcast %>% group_by(batter) %>% dplyr::summarise() %>% inner_join(masterid, by = c("batter" = "mlb_id")) %>%
  select(batter,mlb_name) %>% arrange((mlb_name)) -> possibleBatters

possibleBattersList <- possibleBatters$batter
names(possibleBattersList) <- possibleBatters$mlb_name
```

```{r}
ui <- fluidPage(
  titlePanel("Swing Rate Plot"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("Batter", "Select Batter:",
                  choices = possibleBattersList,
                  selected = "405395"),
      checkboxGroupInput("types",
                         h3("Outcome"),
                         choices = list("X" = "X", "B" = "B", "S" = "S"),
                         selected = c("X", "B", "S"))
    ),
    
    mainPanel(
      plotOutput(outputId = "SwingRatePlot")
    )
  )
)

```

```{r}
server <- function(input, output) {
  SelectedBatterReactive <- reactive({
    req(input$Batter)
    SwingStatcast %>% filter(batter == input$Batter)
  })
  
  output$SwingRatePlot <- renderPlot({
    SelectedBatterResults <- SelectedBatterReactive() %>%
      filter(type %in% input$types)
    
    validate(
      need(nrow(SelectedBatterResults) > 0, "No data available for the selected batter and outcome.")
    )
    
    zones <- SelectedBatterResults %>%
      group_by(zone) %>%
      summarize(
        N = n(),
        right_edge = min(1.5, max(plate_x)),
        left_edge = max(-1.5, min(plate_x)),
        top_edge = min(4, quantile(plate_z, 0.95, na.rm = TRUE)),
        bottom_edge = max(1, quantile(plate_z, 0.05, na.rm = TRUE)),
        swing_rate = sum(swing == TRUE) / n(),
        plate_x = mean(plate_x),
        plate_z = mean(plate_z)
      )
    
    k_zone_plot %+% zones +
      geom_rect(aes(xmax = right_edge, xmin = left_edge,
                    ymax = top_edge, ymin = bottom_edge,
                    fill = swing_rate, alpha = swing_rate)) +
      geom_text_repel(size = 3, aes(label = round(swing_rate, 2))) +
      scale_fill_gradient(low = "blue", high = "red") +
      scale_color_manual(values = c("white", "black")) +
      ggtitle("Swing Per Pitch during July 2019")
  })
}

```

```{r}
shinyApp(ui = ui, server = server)
```

