---
title: "Week 5"
output: html_document
date: "2024-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(Lahman)
library(rvest)
```

```{r}
scrapePlayerBIO <- function(bbrefID){

FirstInitial <- substring(bbrefID, 1, 1)
url <- paste("https://www.baseball-reference.com/players/", FirstInitial, "/", bbrefID, ".shtml", sep = "")
Webpage <- read_html(url)

##Position
Webpage %>% html_nodes("div#info p") %>% html_text() -> WebsiteData
WebsiteData %>% strsplit('\n') -> Positionline
Positionline [[1]][3] %>% trimws() -> Position

##High School
for(i in 1: length(WebsiteData)){
  if(grepl("High School:", WebsiteData[i], fixed = TRUE)){
  print(WebsiteData[i])
  WebsiteData[i] %>% strsplit(":", fixed = TRUE) -> highschoolline
  highschoolline[[1]][2] %>% trimws() -> highschool
  break
  }
}
return(tibble(bbrefID=bbrefID, Position=Position, highschool=highschool))
}
```

```{r}
## Lahman
library(Lahman)
Batting %>%
  filter(yearID == "1986") %>%
arrange(desc(SB)) %>% head(10) %>% pull(playerID)
```
```{r}
Top10StolenBases <- Batting %>%
  filter(yearID == 1986) %>% group_by(playerID) %>%
  summarize(SB) %>%
  arrange(desc(SB)) %>% head(10) %>%
  pull(playerID)

People %>%
  filter(playerID %in% Top10StolenBases) %>%
  pull(bbrefID) -> StolenBasesBBref

Top10SBScrape <- function(Top10StolenBases){
  Top10SBTibble <- tibble(bbrefID=bbrefID, Position=Position, highschool=highschool)
  for(i in 1:length(Top10StolenBases)) {
  scrapePlayerBIO(Top10StolenBases[i]) -> TopSB
  Top10SBTibble %>% bind_rows(TopSB) -> Top10SBTibble
  }
 
  return(Top10SBTibble)
}

```
```{r}
Top10SBScrape(StolenBasesBBref)
```
```{r}
Player2 <- scrapePlayerBIO(StolenBasesBBref[2])
Player3 <- scrapePlayerBIO(StolenBasesBBref[3])
Player4 <- scrapePlayerBIO(StolenBasesBBref[4])
Player5 <- scrapePlayerBIO(StolenBasesBBref[5])
Player6 <- scrapePlayerBIO(StolenBasesBBref[6])
Player7 <- scrapePlayerBIO(StolenBasesBBref[7])
Player8 <- scrapePlayerBIO(StolenBasesBBref[8])
Player9 <- scrapePlayerBIO(StolenBasesBBref[9])
Player10 <- scrapePlayerBIO(StolenBasesBBref[10])
```
```{r}
bind_rows(Player2,Player3,Player4,Player5,Player6,Player7,Player8,Player9,Player10) -> FinalFinishedTibble
```

```{r}
write_csv(FinalFinishedTibble, "StolenBaseLeaders.csv")
```



